### ISSUE TITLE
New RSO verification

### ISSUE THREAD

**Issue by FrostySo** [5z3f/lol-re-notes#1]
Endpoint : auth.riotgames.com / token

client_assertion_type:urn:ietf:params:oauth:client-assertion-type:jwt-bearer
client_assertion:{token}
grant_type:password
username:{user}
password:{pass}
scope:openid offline_access lol ban profile email phone summoner
X-Riot-DSID:{v4}

Now required a couple extra params. client_id is one of them for "lol" but there is still another that is required. Do you know anything about this? 

EDIT: If you want to know more 

0x0178951C
0x0178954C

in LeagueClient.exe with 
SHA256: 839C78BDC7E7AF997BE03E1A32FEDDCC4BAEE0BC99314CF04C5B399B499AFC8B
MD5: 21069D093C5D92890E8FD2153310A4E6

**Comment by 5z3f** [comment]
Oh sorry, somehow I didn't get a notification..
Legacy login shouldn't be used anymore, to grant permission for league endpoints you should do following:
`Create Session -> Authorize as RiotClient-> Authorize as LeagueClient`

```
    def keystoneAuthorizeAsLeagueClient(self, region: str=None):
        headers = {
            'Accept-Encoding': 'deflate, gzip', 
            'user-agent': self.userAgent('rso', 'RiotClient'), 
            'Cache-Control': 'no-cache', 
            'Content-Type': 'application/json', 
            'Cookie': f'did={self.did}; ssid={self.ssid}; clid={self.clid}; sub={self.sub}; ssalt={self.ssalt};', 
            'Accept': 'application/json'
        }

        payload = {
            'acr_values': 'urn:riot:bronze',
            'claims': "{\r\n    \"id_token\": {\r\n        \"rgn_EUW1\": null\r\n    },\r\n    \"userinfo\": {\r\n        \"rgn_EUW1\": null\r\n    }\r\n}".replace('EUW1', region),
            'client_id': 'lol',
            'nonce': self.randomString(22, False),
            'redirect_uri': 'http://localhost/redirect',
            'response_type': 'token id_token',
            'scope': 'openid offline_access lol ban profile email phone birthdate'
        }

        r = requests.post("{0}/api/v1/authorization".format(self.issuer), headers=headers, json=payload)
        self.accessTokenLOL, self.idTokenLOL = re.search("access_token=(.*)&scope=.*id_token=(.*)&token_type=", r.text).groups()
```
Issuer is in league client config and UserAgent can be found easily in memory.

**Comment by FrostySo** [comment]
> Oh sorry, somehow I didn't get a notification..
> Legacy login shouldn't be used anymore, to grant permission for league endpoints you should do following:
> `Create Session -> Authorize as RiotClient-> Authorize as LeagueClient`
> 
> ```
>     def keystoneAuthorizeAsLeagueClient(self, region: str=None):
>         headers = {
>             'Accept-Encoding': 'deflate, gzip', 
>             'user-agent': self.userAgent('rso', 'RiotClient'), 
>             'Cache-Control': 'no-cache', 
>             'Content-Type': 'application/json', 
>             'Cookie': f'did={self.did}; ssid={self.ssid}; clid={self.clid}; sub={self.sub}; ssalt={self.ssalt};', 
>             'Accept': 'application/json'
>         }
> 
>         payload = {
>             'acr_values': 'urn:riot:bronze',
>             'claims': "{\r\n    \"id_token\": {\r\n        \"rgn_EUW1\": null\r\n    },\r\n    \"userinfo\": {\r\n        \"rgn_EUW1\": null\r\n    }\r\n}".replace('EUW1', region),
>             'client_id': 'lol',
>             'nonce': self.randomString(22, False),
>             'redirect_uri': 'http://localhost/redirect',
>             'response_type': 'token id_token',
>             'scope': 'openid offline_access lol ban profile email phone birthdate'
>         }
> 
>         r = requests.post("{0}/api/v1/authorization".format(self.issuer), headers=headers, json=payload)
>         self.accessTokenLOL, self.idTokenLOL = re.search("access_token=(.*)&scope=.*id_token=(.*)&token_type=", r.text).groups()
> ```
> 
> Issuer is in league client config and UserAgent can be found easily in memory.

Thanks for the reply, though lol. I already found it, hence why I closed it. 

You don't need to pass in any cookies though. They don't seem to check for it/use it for anything important to get the token. Maybe you need it for some other stuff but afaik, It only checks for the nonce, claims, acr_values, clienid it and that's about it.

**Comment by 5z3f** [comment]
> You don't need to pass in any cookies though. They don't seem to check for it/use it for anything important to get the token. Maybe you need it for some other stuff but afaik, It only checks for the nonce, claims, acr_values, clienid it and that's about it.

Yes, I know that. By making it 1:1 I simply don't want to get my accounts potentially flagged as it was happening in the legacy login endpoints.

**Comment by FrostySo** [comment]
True that. I guess it's worth it to not take a risk. 

Thanks again for willing to help!
